### ISSUE TITLE
personal lib

### ISSUE THREAD

**Issue by ekfchan** [ekfchan/BNG-FragileSiteRepair#1]
split_xmap_standalone.pl, line 6
`use lib "/home/users/psheth/perl5/lib/perl5";`

Can we rather list all essential modules needed in the README with info on tricky installs in the WIKI? 
Can we replace any of the modules with existing ones that get shipped with IrysSolve on the Phi system?

**Comment by palakpsheth** [comment]
- removed use lib from split_xmap
- updated README to include commands to install required dependencies
